services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 2s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6
    ports:
      - "6379:6379"
