services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 2s
      timeout: 10s
      retries: 5
    env_file:
      - path: ./.env
        required: true

  redis:
    image: redis:7-alpine
    env_file:
      - path: ./.env
        required: true
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=sqs,s3
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  dd-agent:
    image: gcr.io/datadoghq/agent:7
    env_file:
      - path: ./.env
        required: true
    volumes:
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /proc/:/host/proc/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8125:8125/udp"
      - "8126:8126"
