services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 2s
      timeout: 10s
      retries: 5
    env_file:
      - path: ./.env
        required: true
  redis:
    image: redis:7-alpine
    env_file:
      - path: ./.env
        required: true
    ports:
      - "6379:6379"
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -s http://localhost:9200/_cluster/health | grep -q ''"status":"green"''',
        ]
      interval: 10s
      timeout: 10s
      retries: 5
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: wld-usernames-opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      - opensearch
  dd-agent:
    image: gcr.io/datadoghq/agent:7
    env_file:
      - path: ./.env
        required: true
    volumes:
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /proc/:/host/proc/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8125:8125/udp"
      - "8126:8126"
