services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 2s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:7
    command: redis-server --requirepass password --tls-replication "yes" --port 0 --tls-port 6379 --tls-cert-file /certs/redis.crt --tls-key-file /certs/redis.key --tls-ca-cert-file /certs/ca.crt
    ports:
      - "6379:6379"
    volumes:
      - ./certs:/certs
