name: Build

on:
    push:
        branches:
            - main

permissions:
    contents: read
    packages: write

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ github.repository }}
                  tags: |
                      type=ref,event=tag
                      type=ref,event=branch
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: '${{ github.actor }}'
                  password: '${{ secrets.GITHUB_TOKEN }}'

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v6
              with:
                  push: true
                  context: .
                  file: ./Dockerfile
                  cache-from: type=gha
                  cache-to: 'type=gha,mode=max'
                  tags: '${{ steps.meta.outputs.tags }}'
                  labels: '${{ steps.meta.outputs.labels }}'
                  build-args: |
                        SQLX_OFFLINE: true
              env:
                  DOCKER_BUILD_SUMMARY: false
                  DOCKER_BUILD_RECORD_UPLOAD: false
                  SQLX_OFFLINE: true
